language: node_js
node_js:
    - 'lts/*'

install: npm ci

script:
    - npm test
    - npm run build:deploy

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $TOKEN
    fqdn: vanity-eth.tk
